[package]
name = "mbedtls"
description = "Lightweight crypto and SSL/TLS library"
license = "Apache-2.0"
homepage = "https://github.com/Mbed-TLS/mbedtls"
category = "library"

[build]
type = "cmake"
options = [
    "-DENABLE_TESTING=OFF",
    "-DENABLE_PROGRAMS=OFF",
    "-DUSE_SHARED_MBEDTLS_LIBRARY=OFF",
    "-DUSE_STATIC_MBEDTLS_LIBRARY=ON",
]
